# .render.yaml

services:
  - type: web
    name: gobowl-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
